// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT5VPfLHVLPzFvRtcVJN7FN-i0wjKwztg',
    appId: '1:779311544450:web:92460406a06fd47356dc9b',
    messagingSenderId: '779311544450',
    projectId: 'salud-43912',
    authDomain: 'salud-43912.firebaseapp.com',
    storageBucket: 'salud-43912.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwL2iiQ7zANeOQIvZA5ucbOmyQSX3PCUg',
    appId: '1:779311544450:android:8c9f53a80835d06356dc9b',
    messagingSenderId: '779311544450',
    projectId: 'salud-43912',
    storageBucket: 'salud-43912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe1DHjlN9tVwR98Ynx6xiljg134jYAdq4',
    appId: '1:779311544450:ios:72a5a495a6e040af56dc9b',
    messagingSenderId: '779311544450',
    projectId: 'salud-43912',
    storageBucket: 'salud-43912.appspot.com',
    iosClientId:
        '779311544450-6civp2ksuif29l4vcuc67cu6lk6vcejf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe1DHjlN9tVwR98Ynx6xiljg134jYAdq4',
    appId: '1:779311544450:ios:72a5a495a6e040af56dc9b',
    messagingSenderId: '779311544450',
    projectId: 'salud-43912',
    storageBucket: 'salud-43912.appspot.com',
    iosClientId:
        '779311544450-6civp2ksuif29l4vcuc67cu6lk6vcejf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dientes',
  );
}
